### ISSUE TITLE
Proof of concept with Cumulus on NGAP

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/nucleus#13]

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda is deploying cumulus on NGAP. There was an error using docker compose so he is trying the terraform method which worked 80% but there remaining failures.

**Comment by jimmie** [comment]
Progress on-going through discussions w/ Jason W (NGAP)

**Comment by jordanpadams** [comment]
Status: @ramesh-maddegoda Jason W. fixed an issue server side and is working on redeployment. may be delayed until next sprint.

**Comment by jimmie** [comment]
Cumulus instance now available but not self-installed - needed to be installed by Jason.

**Comment by jimmie** [comment]
Jason (NGAP) still working on Cumulus deployment.

**Comment by ramesh-maddegoda** [comment]
Had a detailed discussion with a Unity project team that uses Cumulus, in order to understand the value additions and pain points related with Cumulus.

Some value additions and pain points shared by the Unity team that uses Cumulus.

Value Additions:
- There are several lambda functions available from Cumulus that can reduce the development time related with moving files, archiving etc.
- The documentation is well written
- There are several existing integrations available with NASA systems such as Earthdata Login and ESDIS Metrics System (EMS)
- Cumulus uses an AWS API Gateway integrated with Lambda to enable secure communication

Pain Points:
- The data model of Cumulus cannot be directly reused for a new project (E.g: PDS) without introducing updating the Cumulus data model
- There is no multiple version support for data files
- Processing very large files (50 GB+) with Cumulus lambda function can cause performance issues 
- The terraform state files should be shared between those who want to deploy a new workflow

Added more slides to the Trade Study slide deck based on recent findings.
https://docs.google.com/presentation/d/1xbaJQ6e9jg3XZn2VXsfygKlUMZ_gW4c_t65Vkq0daKI/edit#slide=id.g195b29ef5c2_1_144
