### ISSUE TITLE
Design queuing service for streaming data into Nucleus

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#60]

**Comment by tloubrieu-jpl** [comment]
- One issue to test s3 notification on NGAP (blocking)
- Moving Messenger data on our s3 bucket

**Comment by tloubrieu-jpl** [comment]
So far the idea is:

- s3 notify of a new file
- a component moves the file to EFS staging space and send a new notification (SQS)

Still other issues with the NGAP deployment.
-

**Comment by tloubrieu-jpl** [comment]
Discussions on-going to interface DUM with Nucleus for the management of event triggering the workflows.

**Comment by ramesh-maddegoda** [comment]
Completed design and saved as a lucid chart

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda @jordanpadams I am addiing here a proposal for using dynamoDB for the incoming file management:

The keys for the buckets in DynamoDB are the absolute path to the files on s3.

We consider 3 buckets:
1.	`incomplete_products`: the xml labels, only for incomplete products, the value of the record is the list of the missing data files, using their absolute path. 
2.	`expected_data_files`: the expected data files, not received yet. The value of the record is the key of the incomplete product which expects it.
3.	`received_data_files`: the received data files, all of them because we don't know how many time they can be used in a label. The value does not matter for the primary nucleus need but we can add ids and checksums.

When the lambda work it waits for **a)** xml file or **b)** other files (data files)

**a) when a xml file is received:**
```
We try to complete it with the files found in `received_data_files` bucket using the file absolute path as a key
If complete: 
    The product is moved to EFS and pushed to nucleus queue
    The product is removed from the `incomplete_products` bucket
Else (incomplete):
    We create a record in `incomplete_products` bucket. Value is the list of expected data files not found, e.g missing_data_files: [<full path1>, <full path2>, ...]
    We add each missing data file in the `expected_data_files`. Value is the key to the xml label in `incomplete_products` bucket (e.g. product: <full path to xml>)
```
**b) when a data file is received:**
```
We add it to the `received_data_files` bucket.
We look up in the `expected_data_files` bucket if it was expected
If the data file is expected:
    We get the key of the product found in the bucket `expected_data_files` record value
    We remove the record from the `expected_data_files` bucket
    We query the `incomplete_products` bucket with the key found and we remove the missing data file from the list
    If the list of missing data files is empty:
        The product is moved to EFS and pushed to the queue
        The product is removed from the `incomplete_products` bucket
```

The performance of the algorithm should be good and fully scalable since we only retrieve the record by their key which is what dynamoDB is optimized for.
