### ISSUE TITLE
MCP Pilot: Pilot Nucleus Deployment for CSS and MESSENGER MDIS Data

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#66]
## 💡 Description

- https://github.com/NASA-PDS/nucleus/issues/52
- https://github.com/NASA-PDS/nucleus/issues/53
- ~https://github.com/NASA-PDS/nucleus/issues/54~ 75% complete. tabled for CSS ingestion. will revisit in B15.0
- https://github.com/NASA-PDS/nucleus/issues/75
- https://github.com/NASA-PDS/nucleus/issues/74

**Comment by jordanpadams** [comment]
@ramesh-maddegoda Here is your parent Epic for the Nucleus deployment. Happy to change the scope if we want to work with a different data set. Or maybe an additional sub-task will be to first just test out whether or not this works in MCP, then the overall pilot is to deploy this for MESSENGER.

**Comment by jordanpadams** [comment]
@ramesh-maddegoda Here is your parent Epic for the Nucleus deployment. Happy to change the scope if we want to work with a different data set. Or maybe an additional sub-task will be to first just test out whether or not this works in MCP, then the overall pilot is to deploy this for MESSENGER.

**Comment by jordanpadams** [comment]
📆 October status: Demo for SBN and CSS completed on 10/27. Work ongoing to load more data operationally and prepare for beta production usage

**Comment by jordanpadams** [comment]
📆 November status: Delayed 2 sprints due to issues with cost associated with initial design of CSS processing. https://github.com/NASA-PDS/nucleus/issues/74 . No impact on delivery expected.

**Comment by jordanpadams** [comment]
📆 December status: Delayed 1 additional sprint. Need to process data through Nucleus, but software is ready. No impact on delivery.

**Comment by tloubrieu-jpl** [comment]
@viviant100 , what would be the next step on that ?

**Comment by jordanpadams** [comment]
@ramesh-maddegoda have we loaded all MESSENGER data?

**Comment by ramesh-maddegoda** [comment]
> @ramesh-maddegoda have we loaded all MESSENGER data?

@jordanpadams , when loading the messenger data I found the following bug.
https://github.com/NASA-PDS/nucleus/issues/83

I have loaded the following messenger data directories to MCP OpenSearch. There were few missing products due to the bug above. I will load following directories to JPL AWS too.

MESSDEM_1001/ 
MSGRMDS_1001/
MSGRMDS_4001/
MSGRMDS_5001/
MSGRMDS_6001/
MSGRMDS_7001/
MSGRMDS_7101/                           
MSGRMDS_7201/
MSGRMDS_7301/
MSGRMDS_8001/

Also, the following 2 directories are very large and I get timeouts due to AWS credential expiry. So , I use aws s3 sync command to copy data time to time (when there are timeouts).due to . 

MSGRMDS_2001/ - 1.4 TiB
MSGRMDS_3001/ - 3.3 TiB

**Comment by jordanpadams** [comment]
📆 02/2024 status: In work. On schedule for completion by end of sprint.
